### ISSUE TITLE
Things to be decided before initial stable release

### ISSUE THREAD

**Issue by ikitommi** [metosin/malli#116]
* [x] Recursive schemas #96 
* [x] Inherit schema properties from map entries? #86
* [x] explain data to be symmetric with `LensScema` options #238 
* [x] Does value parsers (e.g. spec conform) effect the api? --> can be done later
* [x] Support by default type-schemas, predicate-schemas or both? #25-> both, for alpha
* [x] Customizable default options #228 --> later
* [x] Open or Closed maps by default #31
* [x] Re-visit priority of encoders & decoders #99

**Comment by green-coder** [comment]
I suggest to add "recursive models" to the list.

**Comment by ikitommi** [comment]
Added that and #86 to the list.

**Comment by ikitommi** [comment]
one to go.

**Comment by ikitommi** [comment]
two to go.

**Comment by green-coder** [comment]
Something special with sequences,  it's that parsing a data structure can result in multiple ways to match the data, i.e. to put a name on the parts of the data.

It is useful to keep that in mind and see if it affects the API before making a release.

**Comment by ikitommi** [comment]
Parsing (and Schema-variants with named branches) could be implemented as an increment using either `-explain` or `-transform`. Both could be non-breaking increments on top of the initial api, but might not -> I'll add to the list.

Using `-explain` (to optionally collect both the successful parse-tree & errors) would be interesting, as we could return partial parse trees with errors in place. 

compared to spec:

```clj
(require '[clojure.spec.alpha :as s])

(def spec (s/+ (s/cat :odds (s/+ odd?)
                      :even (s/? even?))))

(s/conform spec [1 3 5 100 1 20])
; [{:odds [1 3 5], :even 100} {:odds [1], :even 20}]

(s/explain-data spec [1 3 5 100 1 20 40])
;#:clojure.spec.alpha{:problems ({:path [:odds], :pred clojure.core/odd?, :val 40, :via [], :in [6]}
;                                {:path [:odds], :pred clojure.core/odd?, :val 40, :via [], :in [6]}
;                                {:path [:odds], :pred clojure.core/odd?, :val 40, :via [], :in [6]}
;                                {:path [:odds], :pred clojure.core/odd?, :val 40, :via [], :in [6]}),
;                     :value [1 3 5 100 1 20 40]}
```

**Comment by ikitommi** [comment]
closing this, there is a internally working prototype of regeexs, work to get integrated into `explain` and potentially new `destructure` and `restructure`. but can be a later additon to the api,
